import { Box } from '@mui/material';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import EmotionRegistry from '../theme/EmotionRegistry';
import MUIProvider from '../theme/MUIProvider';
import Sidebar from './components/Sidebar';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <EmotionRegistry>
          <MUIProvider>
            <Box sx={{ display: 'flex' }}>
              <Sidebar />
              <Box sx={{ marginLeft: 240, flexGrow: 1, p: 3 }}>
                {children}
              </Box>
            </Box>
          </MUIProvider>
        </EmotionRegistry>
      </body>
    </html>
  );
}
